services:
  app:
    container_name: PAOJ
    build: .
    stdin_open: true     # Permite input din terminal (echivalent cu -i)
    tty: true            # Aloca un terminal (echivalent cu -t)
    depends_on:
      - db
    environment:
      DB_HOST : db
      DB_PORT : 5432
      DB_USER : postgres
      DB_PASSWORD : postgres
    volumes:
      - ./src:/app/src
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD : postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5431:5432 
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
