services:
  app:
    hostname: docker
    container_name: PAOJ
    build: .
    stdin_open: true     # Permite input din terminal (echivalent cu -i)
    tty: true            # Aloca un terminal (echivalent cu -t)
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
