apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankingApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankingApp
  template:
    metadata:
      labels:
        app: bankingApp
    spec:
      containers:
      - name: bankingApp
        image: buscoveanuvictor/raspberrypi:latest
        ports:
        - containerPort: 8080
    